-- Migration 066: Per-tenant AI voice prompt snapshot
--
-- ─── CONTEXT ─────────────────────────────────────────────────────────────────
--
-- VOICE-FIX-6 introduces per-tenant voice agent prompts generated by Claude
-- from each tenant's own DB context (services, rates, hours, resources, staff,
-- voice_instructions, branding). The generated prompt is stored as a JSONB
-- snapshot on the tenants table.
--
-- The snapshot shape:
--
--   {
--     "prompt": "<full rendered system prompt text>",
--     "generated_at": "2026-05-09T12:34:56Z",
--     "model": "claude-sonnet-4-6",
--     "source_data_hash": "<sha256 of input businessContext>",
--     "version": 1
--   }
--
-- When a voice session starts, utils/voiceContext.js checks:
--   1. Is the tenant in the voice-feature whitelist? (currently birdie-golf only)
--   2. Is voice_prompt_snapshot non-null and contains a "prompt" field?
-- If both true → use the snapshot's prompt as the base, append a small
-- dynamic block (current customer, today's date, language lock, currency rules).
-- If either false → fall back to the legacy code-rendered voiceContext (V4
-- baseline: the working pre-VOICE-FIX-5 path).
--
-- This means:
--   - No tenant breaks. The 22 tenants without a snapshot keep running V4.
--   - Birdie tests the new path. Once stable, we onboard others.
--   - The owner can re-generate at any time (admin endpoint POST .../generate)
--     or hand-edit (admin endpoint PUT) without code changes.
--
-- ─── WHAT THIS MIGRATION DOES ────────────────────────────────────────────────

ALTER TABLE tenants
  ADD COLUMN IF NOT EXISTS voice_prompt_snapshot JSONB NULL;

-- No backfill — all existing tenants stay NULL and use the legacy fallback.
-- Index not needed: this column is only read on voice session start,
-- and lookup is by tenant id (already PK-indexed).

COMMENT ON COLUMN tenants.voice_prompt_snapshot IS
  'JSONB snapshot of the tenant-specific AI voice agent system prompt. Generated by utils/voicePromptGenerator.js from tenant business context. NULL = use code-rendered legacy fallback. Schema: { prompt, generated_at, model, source_data_hash, version }.';
